# BASELINE — mirrors nginx install defaults
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        off;       # default: OFF
    tcp_nopush      off;       # default: OFF
    keepalive_timeout  65;     # default: 65s
    gzip  off;                 # default: disabled

    server {
        listen       80;
        server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }
    }
}